export const RECEIVE_APP_DATA = 'RECEIVE_APP_DATA';
export const POP_APP_NOTIFICATION = 'POP_APP_NOTIFICATION';
export const PUSH_APP_NOTIFICATION = 'PUSH_APP_NOTIFICATION';

export const CREATE_DECK = 'CREATE_DECK';
export const RECEIVE_DECKS = 'RECEIVE_DECKS';
export const SET_DECK_FORM_TITLE = 'SET_DECK_FORM_TITLE';
export const SET_DECK_FORM_TITLE_ERROR = 'SET_DECK_FORM_TITLE_ERROR';

export const CREATE_CARD = 'CREATE_CARD';
export const RECEIVE_CARDS = 'RECEIVE_CARDS';
export const SET_CARD_FORM_ANSWER = 'SET_CARD_FORM_ANSWER';
export const SET_CARD_FORM_QUESTION = 'SET_CARD_FORM_QUESTION';
export const SET_CARD_FORM_ANSWER_ERROR = 'SET_CARD_FORM_ANSWER_ERROR';
export const SET_CARD_FORM_QUESTION_ERROR = 'SET_CARD_FORM_QUESTION_ERROR';
